PVP-41
PVP-K410/Calendar pull request #19
Opened 2024-03-08 14:07 UTC by KhajiitLikeToSneak

Added filters functionality
Design could be updated later on

2024-03-08 15:03 UTC, klaidoshka requested changes

2024-03-08 15:03 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/filter/FilterViewModel.kt
> +            userService.merge(updatedUser)
Separation from variables initialization is required.

2024-03-08 15:03 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/filter/FilterViewModel.kt
> +            _user.emit(updatedUser)
Separation required.

2024-03-08 23:15 UTC, vytjar approved these changes
Functionality seems okay. Will need a pop up or something in the future to inform the user that changes have been applied.

2024-03-11 06:51 UTC, klaidoshka approved these changes

2024-03-11 06:51 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/filter/Filter.kt
> +            FlowRow(
Empty single line could be added to separate components of the same level.

2024-03-11 06:51 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/filter/Filter.kt
> +                    }
Whole card with its children components may not be correctly indented. `Control+Alt+L` would fix this. I think 4 spaces are missing.

2024-03-11 06:51 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/filter/Filter.kt
> +    val activities: List<String> = SportActivity.values().map { it.title }
Could be transfered out of the activities filter component to make it singleton (computed only once) or into `LaunchedEffect` block to make it recompute only after user value changes, but not every time the component is rerendered.

2024-03-11 10:37 UTC, merged