PVP-171 PVP-173 Add points calculation algorithm and points adding functionality
PVP-K410/Calendar pull request #55
Opened 2024-03-22 18:22 UTC by klaidoshka

# Changes
- Refactored Task model to contain Points model which holds:
  - claimedAt (LocalDateTime)
  - value (Int)
- Points of the task are precalculated upon task creation
- User gets points after completing a task. Single time.
- Task creation is now left to the service instead of creating them manually
- Implemented PointService in a very basic way

# Question
- Should the algorithm of PointService be further improved? Should I assign some index to SportActivity (where each activity would hold variating value between 0~10) and it would be used to some extent in the points calculation when determining how many points to give for task duration, distance? Since some activities are quite hard to do, so in a way they should give more points.

2024-03-22 19:04 UTC, KhajiitLikeToSneak commented
> # Question
> * Should the algorithm of PointService be further improved? Should I assign some index to SportActivity (where each activity would hold variating value between 0~10) and it would be used to some extent in the points calculation when determining how many points to give for task duration, distance? Since some activities are quite hard to do, so in a way they should give more points.

I think it would be more fair and more rewarding for users who complete harder activities. So yes?

2024-03-22 19:07 UTC, klaidoshka commented
> > # Question
> > 
> > * Should the algorithm of PointService be further improved? Should I assign some index to SportActivity (where each activity would hold variating value between 0~10) and it would be used to some extent in the points calculation when determining how many points to give for task duration, distance? Since some activities are quite hard to do, so in a way they should give more points.
> 
> I think it would be more fair and more rewarding for users who complete harder activities. So yes?

Will take care of it tomorrow.

2024-03-23 16:36 UTC, vytjar requested changes
There is a problem with the forms. Even if the activity should not support distance metrics - the user is allowed to choose the distance. For example boxing for 100km.

Another problem is that when you calculate distance points, even if the ratio is 0 it still credits max points, as the formula (cosh(ln(distance * ratio))) returns infinity when distance * ratio = 0. This might not be a problem, if during task creation we would not allow users to set distance for activities that should not support the distance metric. Or we could skip the calculation if the ratio is 0.

2024-03-23 17:56 UTC, vytjar approved these changes

2024-03-23 18:12 UTC, merged