PVP 109 added task cards fore each type of task
PVP-K410/Calendar pull request #7
Opened 2024-02-28 12:42 UTC by vytjar

Dummy tasks for preview created at TaskScreen.

2024-02-28 13:12 UTC, klaidoshka requested changes

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +){
Single spacing before opening curly brackets should be added. `Ctrl+Alt+L` hotkey should format it automatically.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +    if(mealTask.duration != null){
Same as above regarding the space. Remains throughout the whole file.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +@Composable
Should add an empty single line to separate components and increase readability.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +
Redundant empty line.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +    sportTask: SportTask
Could be named `task`, there are no other type tasks inside anymore and type is known.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +            when {
Two separate actions: `method call` and `when logic body`. Should be separated by a single empty line to increase readability.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +
Redundant empty line.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
>  @Composable
A single empty line should be added.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
Redundant empty line.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +
Redundant empty line.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +
Redundant empty line.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +        ) {
Empty brackets should stay in single line.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +                modifier = Modifier.fillMaxWidth(),
Single parameter within brackets _could_ stay in a single line. Can leave it as it is, if wanted.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +                Text(
A single empty line should be added.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +                    .padding(start = 8.dp)
Single method call should stay within single line.

2024-02-28 13:12 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +    TaskBox(sportTask)
Single empty line should be added to separate different elements (variable, component).
Also, a single empty line (line-break) could be added to the end of the file to support UNIX file endings correctly as everywhere else.

2024-02-28 13:13 UTC, klaidoshka commented on app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt
> +            .border(BorderStroke(1.dp, MaterialTheme.colorScheme.outline))
Multiple parameters should be split into multiple lines.

2024-02-28 21:13 UTC, klaidoshka commented
Lines :211 and :125 _could_ be further modified, but either way, it is way better than before 😊

Also, `#getDurationString` method documentation has triple stars for comment `/***`, I would guess that it was done manually. You can set it automatically by writing `/**` and pressing `ENTER`.

For Java it would also fill parameters, their names, return type, exception type (if it is annotated).
```java
/**
 * <p>This is a simple description of the method. . .
 * <a href="http://www.x.com">X!</a>
 * </p>
 * @param incomingDamage the amount of incoming damage      <-- auto generated, except explanation
 * @return the amount of health hero has after attack       <-- auto generated, except explanation
 * @see <a href="http://www.link_to_jira/HERO-402">HERO-402</a>
 * @since 1.0
 */
 public static int damageHero(int incomingDamage) {
     // ...
 }
 ```
However, for kotlin it is not the case, it seems. Kotlin decided to make documentation comments more free-ish by not setting any template. How to use it to greater extent for better developing experience can be found [here](https://kotlinlang.org/docs/kotlin-doc.html#kdoc-syntax).

2024-02-28 21:13 UTC, klaidoshka approved these changes

2024-02-29 07:07 UTC, KhajiitLikeToSneak approved these changes

2024-02-29 14:21 UTC, merged